<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE  note[

<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>

<note>
  <to>Tove</to>
  <from>Aabhushan</from>  
  <heading>remainde</heading>
  <body>Don't forget me this weekend</body>
</note>