<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE user[

<!ELEMENT user (one)>
<!ELEMENT one (name,contact,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST name fullname ENTITY #IMPLIED>
<!ENTITY name1 "Aabhushan Dhakal">
<!ENTITY name2 "Ayush Dhakal">
]>
<user>
  <one>
    <name fullname="&name1;"></name>
    <contact>123456789</contact>
    <address>dharan 16</address>
  </one>
  <one>
    <name fullname="&name2;"></name>
    <contact>98253762454</contact>
    <address>dharan 12</address>
  </one>
</user>